version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "gokul"          
      POSTGRES_PASSWORD: "1212"
      POSTGRES_DB: "timepeace"
    networks:
      - mydb
    volumes:
      - database-postgres:/var/lib/postgresql/data

  timepeace:
    image: gokulsajeev/docker_timepeace

    restart: on-failure
    environment:
      DB_HOST: "postgres"
      DB_USER: "gokul"
      DB_PASSWORD: "1212"
      DB_PORT: "5432"
      DB_NAME: "timepeace"
    depends_on:
      - postgres
    networks:
      - mydb
    ports:
      - "3000:3000"

volumes:
  database-postgres:

networks:
  mydb:
    driver: bridge