apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres-password: "1212"
  postgres-host: "postgres"
  postgres-db: "timepeace"
  postgres-user: "gokul"
  postgres-port: "5432"